### ISSUE TITLE
How update to 1.1.0.0?

### ISSUE THREAD

**Issue by eduwalecki** [the-hideout/TarkovMonitor#24]
has autoupdate? I tried replace files but got permission error... Thanks!

**Comment by Razzmatazzz** [comment]
Just close the app, delete the old version and put the files from the new version in its place.

**Comment by eduwalecki** [comment]
I managed to update it here. Thank you very much.

It seems that the program was running in the background, and I could only close it by manually searching for the task manager. I think after I tried to load the log file manually, it froze and didn't shut down properly. I'll try to reproduce it, and if I notice anything unusual, I'll update with a new post.

Thank you very much for the development and the great tool for the community!
