### ISSUE TITLE
Error checking for new version: 403 (Forbidden)

### ISSUE THREAD

**Issue by Ryuichiro** [the-hideout/TarkovMonitor#27]
Error checking for new version: Response status code does not indicate success: 403 (Forbidden).
![image](https://github.com/the-hideout/TarkovMonitor/assets/4333206/fa3de0ee-25f4-44c9-b53e-bef47a954444)

**Comment by Razzmatazzz** [comment]
Please download the latest release. This error should go away.

**Comment by Ryuichiro** [comment]
Oh, thought it auto updates.

The current version seems to have a random chance to fail loading stuff, he got it right after a few restarts.
I couldn't find the App's logs to see what the actual exception is.
**1. Start**
![image](https://github.com/the-hideout/TarkovMonitor/assets/4333206/435608e2-a9f6-411e-b86b-6b8ff0c538d9)
**1. Restart**
![image](https://github.com/the-hideout/TarkovMonitor/assets/4333206/3eb0b8fd-9a59-47f4-9347-51695da89a62)
**2. Restart**
![image](https://github.com/the-hideout/TarkovMonitor/assets/4333206/26a7e12a-33a0-4098-9f36-7856c427351f)

**Comment by Ryuichiro** [comment]
As an additional note. it seems the app doesn't close properly. I only noticed it because I got multiple voice notifications.
It's 100% reproducible (at least for me). Just open the app, and close it using the X button in the Windows title bar. If you look for the processes in the Task Manager, you can see them still running.

**Comment by Wraiith32** [comment]
> 

I was going to report a potential memory leak as well. I noticed this on occasion, but trying to see if I can figure out a way to replicate it.

**Comment by Razzmatazzz** [comment]
Since the update check is fixed in the current release and I created a new issue for the app not closing properly, I'm going to close this issue. If your experience of the app not closing properly is different, please contribute your experience in issue #28
