### ISSUE TITLE
Loading Raw Logs page causes memory leak and prevents app closing

### ISSUE THREAD

**Issue by Razzmatazzz** [the-hideout/TarkovMonitor#28]
The app doesn't properly close reliably. The simplest way I've found to replicate the issue is to start the app, open the "Raw Logs" page, and then close the program. The process keeps running. Opening the other pages doesn't do the same thing for me and I'm not sure why.

**Comment by Wraiith32** [comment]
I think the memory leak is caused by MudMenu in the RawLogs screen. If you remove that section, the applications closes out of memory correctly. Not exactly sure what is causing it.

**Comment by Razzmatazzz** [comment]
That's my current understanding as well. If you don't open that page, I believe the app closes normally. Haven't had to to try to figure out why that's the case. One a glance, the page doesn't seem meaningfully different from other pages.
