### ISSUE TITLE
Application Freezes and Throws C# Error After Navigating Back from Messages in Raw Logs via Hamburger Menu

### ISSUE THREAD

**Issue by Carbneth** [the-hideout/TarkovMonitor#29]
When we navigate to "Raw Logs" from the hamburger menu and then return to the "Messages" section, the application becomes unresponsive. Additionally, if we refresh the page using F5, it results in a C# error.

**Comment by Razzmatazzz** [comment]
Related to #28 
For some reason, the Raw Logs page causes strange behavior generally.
