### ISSUE TITLE
unable to open Tarkov monitor correctly

### ISSUE THREAD

**Issue by 758727829** [the-hideout/TarkovMonitor#30]
Just as shown in my screenshot, when I open the software, it displays a white screen without any prompts. Where can I find the error logs?
![image](https://github.com/the-hideout/TarkovMonitor/assets/74652977/0cfbb70a-eb6d-4679-a5c4-e073b22ebf38)

**Comment by Razzmatazzz** [comment]
This seems similar to #22. Still haven't had much time to dig into this. Someone posted what might be a solution in that issue, but I've asked for clarification.

**Comment by Razzmatazzz** [comment]
Closing as likely duplicate of #22.
