### ISSUE TITLE
Times on the Dashboard are off by a factor of 100

### ISSUE THREAD

**Issue by Ryuichiro** [the-hideout/TarkovMonitor#32]
All the times in the Dashboard are declared as seconds, but the value is ~~milliseconds~~ off by a factor of 100.
![RatScanner_2023-08-17_17-42-21](https://github.com/the-hideout/TarkovMonitor/assets/4333206/90b7ced4-04ae-4177-a40a-bb4d7d484a38)

**Comment by Razzmatazzz** [comment]
Hmm seems like something weird is definitely going on, but a matching time of just seven and a half seconds seems way shorter than I'd expect. My experience is that matching times are typically closer to a minute.

**Comment by Ryuichiro** [comment]
Oh yeah, in my head, I just saw an offset but you are right it's off by 2 digits, not 3. That's just weird. ^^

**Comment by Razzmatazzz** [comment]
Strangely, this number appears in a different format in the logs for different users. Is there anything "special" about your version of the game? E.g., region-locked, etc.

**Comment by Ryuichiro** [comment]
Game has a EU "license" and I manually picked EU servers with a low ping.
My best bet would be the Windows region, as Unity may use it to decide how format logged timespans.
(My Windows uses Region Germany)

**Comment by Razzmatazzz** [comment]
Apologies for the delay on this; could you send me the application log for a play session where you loaded into at least one raid?

**Comment by Razzmatazzz** [comment]
@Ryuichiro I believe this has been fixed in the latest release.
