### ISSUE TITLE
Notification to restart "The Guide" despite the quest already done.

### ISSUE THREAD

**Issue by Acecool** [the-hideout/TarkovMonitor#37]
I completed The Guide a few days ago, but since the update I am getting continuous notifications to restart the quest despite it already having been completed.

I don't see The Guide on Tarkov Tracker in Available, Locked or Completed sections. ** Found it by selecting the actual trader instead of viewing ALL. I marked as uncompleted then completed again.. we'll see what happens.

**Comment by Razzmatazzz** [comment]
Did manually marking The Guide as complete resolve the issue?

**Comment by Razzmatazzz** [comment]
Closing for lack of additional information.
