### ISSUE TITLE
Polish: Remove audio notifications for SCAV raids

### ISSUE THREAD

**Issue by Acecool** [the-hideout/TarkovMonitor#38]
There is no sense having a notification for each scav raid, especially as the guide notification has been bugged for me this entire time.

**Comment by Razzmatazzz** [comment]
Unfortunately, at the time when that audio event is triggered, the app doesn't have a way of knowing whether the raid is scav or PMC. By the time the app knows, it's too late to back out. Best solution is to just disable that particular audio warning if you find it annoying.
