### ISSUE TITLE
Notification sounds become buggy when app runs for long period of time

### ISSUE THREAD

**Issue by Acecool** [the-hideout/TarkovMonitor#39]
When notifications play when starting a raid, or to restart quests, etc.. sometimes I'll only hear a blip, or nothing at all. Restarting the app usually works, but if you leave it open for a day or so the audio notifications break down.

**Comment by Razzmatazzz** [comment]
Not sure what would be causing that, so I'm not sure where to start diagnosing the problem. Probably best to just not keep the app running constantly when you're not playing for the time being.

**Comment by Razzmatazzz** [comment]
This was likely resolved along with #28, but let me know if you're still experiencing the issue.
