### ISSUE TITLE
no audio for restarting escort on eu region

### ISSUE THREAD

**Issue by sadd28** [the-hideout/TarkovMonitor#43]

**Comment by Razzmatazzz** [comment]
To be sure I understand the issue, is all of the following true?

- You were using a Tarkov Tracker API token with Tarkov Monitor
- You have the Tarkov Monitor option enabled for warning you to restart failed tasks
- You failed Escort
- You did not restart Escort
- You loaded into a raid but did not receive the audio warning to restart failed tasks
