### ISSUE TITLE
There is no content at on program launch

### ISSUE THREAD

**Issue by VladimirRylov** [the-hideout/TarkovMonitor#48]
I Do have Logs folder. 

![image](https://github.com/the-hideout/TarkovMonitor/assets/55760201/eaa8ea38-e63f-4335-989b-3b847eb828aa)

**Comment by Razzmatazzz** [comment]
Could be a similar problem to #22. Could you try the solution in that issue of installing/re-installing WebView2?

**Comment by VladimirRylov** [comment]
Ok, so after reinstalling WebView2 (deleting reg keys and installing via exe), now when i launch the app, i have the installer for web View Pop-Up every time installing already installed WebView2 and then same problem.

> Could be a similar problem to #22. Could you try the solution in that issue of installing/re-installing WebView2?

**Comment by VladimirRylov** [comment]
Ok, so after reinstalling WebView2 (deleting reg keys and installing via exe), now when i launch the app, i have the installer for web View Pop-Up every time installing already installed WebView2 and then same problem.

**Comment by VladimirRylov** [comment]
Fixed after fully deleting the TarkovTracker app, and unziping it again. Now it's working.
