### ISSUE TITLE
Using start minimized option causes app to close

### ISSUE THREAD

**Issue by TDougy52** [the-hideout/TarkovMonitor#51]
I am experiencing an issue where the app doesn't actually launch as a window. When I launch it, the Tarkov.Dev visual does get seen but then there is a quick blink of an app on the taskbar then it is gone. I see it running in task manager but the monitor window itself is not running. Is there something I am missing? This is off a completely new extract.

**Comment by Razzmatazzz** [comment]
I'm guessing you're having the same issue as #22. Try the solution in one of the comments to that issue: https://github.com/the-hideout/TarkovMonitor/issues/22#issuecomment-1679881378

**Comment by f1n-b** [comment]
I'm having this issue too, I don't believe it is the same as the issue mentioned. This has happened since selecting the launch minimized option. When opening the program the splash screen is displayed and then goes away leaving no window behind at all. The program is executing correctly however, and still operates as expected. Any help on how to make the window appear would be appreciated.

**Comment by Razzmatazzz** [comment]
> I'm having this issue too, I don't believe it is the same as the issue mentioned. This has happened since selecting the launch minimized option. When opening the program the splash screen is displayed and then goes away leaving no window behind at all. The program is executing correctly however, and still operates as expected. Any help on how to make the window appear would be appreciated.
> 
> Just to be clear, I have followed the instructions in #22 and this has not resolved the issue for me.

Is there no icon in the system tray that you can double-click?

**Comment by f1n-b** [comment]
No, when launching just after the splash screen disappears it flashes up in the system tray for a fraction of a second and then is never seen again.

**Comment by TDougy52** [comment]
I extracted to a new folder and re-input my token and made sure not to set the startup minimized option to yes. It works perfectly fine now.

**Comment by f1n-b** [comment]
I deleted it and reinstalled. It opened correctly for the first time. I ensured the start minimized options was not selected and then closed the app. I could then reopen it successfully. However, after reselecting the start minimized option when opening again it exhibits the same behaviour as mentioned above.

**Comment by Razzmatazzz** [comment]
@f1n-b to be clear, the app is briefly showing in your _system tray_ and then closing, not briefly showing up in your _task bar_ and then disappearing?
