### ISSUE TITLE
Scav Timer out of Raid

### ISSUE THREAD

**Issue by Killertom63** [the-hideout/TarkovMonitor#52]
Having a verbal "Scav raid ready" when out of Raid would be nice. Sometimes I've got Tarkov in the background waiting to do scav runs, just helps out.

**Comment by Razzmatazzz** [comment]
This is a neat idea, but it's not really feasible to do accurately. Scav cooldown is affected by intelligence center, which is easy enough to check via Tarkov Tracker and compute. But it's also affected by your scav karma (Fence rep), and as far as I know, there isn't anywhere that information is available. So if we implemented a timer, it would always be off according to whatever scav cooldown benefits (or penalties) each user gets from their scav karma.

**Comment by Killertom63** [comment]
Maybe could base it mainly off Intell center. And have users add their Scav rep into the program? 0.1 isn't going to change much in terms of time?

**Comment by Razzmatazzz** [comment]
Adding a setting for scav karma is doable. It can actually have a huge impact; if someone is at maximum negative karma, their timer is six times the default.

**Comment by Killertom63** [comment]
Oh I meant like if they go up or down by 0.1 they will probably fix it in the app when it's massively off or something. :) Eitherway, I'd love to see this
