### ISSUE TITLE
Start with windows or tarkov?

### ISSUE THREAD

**Issue by Killertom63** [the-hideout/TarkovMonitor#53]
Could the program be made to open with Tarkov? Or with startup on windows?

**Comment by Razzmatazzz** [comment]
To launch the app when Tarkov starts, the app would basically already have to be running. As for starting with windows, that's a fairly trivial thing for anyone to do:
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
