### ISSUE TITLE
Unable to find First Time Setup logs for custom install directory

### ISSUE THREAD

**Issue by messenger-sean** [the-hideout/TarkovMonitor#58]
I have Tarkov installed in a custom location (on the G: drive), and attempting to run `Read Past Logs` gives an error. 

![image](https://github.com/the-hideout/TarkovMonitor/assets/4318057/76325bd4-7654-4fa5-8a6b-e6e5d7c269f0)

The logs do seem to exist, as going to "Raw Logs" tab and then "+" sign, and then "Open Logs Folder" shows a bunch of .txt files inside a folder, which is in a folder of other log directories.

**Comment by Razzmatazzz** [comment]
This should be resolved with the latest release.
