### ISSUE TITLE
First Time Setup issue reading logs

### ISSUE THREAD

**Issue by CBTB11235813** [the-hideout/TarkovMonitor#60]
Installed TarkovMonitor today, tried to read past log files to sync my progress so far. Got this error message:

![image](https://github.com/the-hideout/TarkovMonitor/assets/26905882/b30ac7fb-2dde-4c40-a26d-46b57b429383)

What I believe is the relevant error message here, I can post the full log if needed.

```
> > See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at TarkovMonitor.Blazor.Pages.RawLogs.ForceReadDialog.Submit() in TarkovMonitor\Blazor\Pages\RawLogs\ForceReadDialog.razor:line 81
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
> 
```

**Comment by Razzmatazzz** [comment]
If you click Continue and go back to the app's messages, are any errors shown there?

**Comment by CBTB11235813** [comment]
Well, I am not sure what is different now. Earlier I had restarted the app, game, and my desktop to see if that would fix anything. It didn't so I played for a couple hours. I just tried to recreate the issue to see if there were any errors in the messages tab, and instead got this:


![image](https://github.com/the-hideout/TarkovMonitor/assets/26905882/059d2da2-e35e-4cc3-ae28-dff64cd6dbca)

**Comment by CBTB11235813** [comment]
The only thing I can think of that I changed was I recreated the API token from Tarkov Tracker to give it full permissions. I tried removing the token entirely to isolate the problem, in case it had something to do with the Tracker website. No changes, had the same error

**Comment by Razzmatazzz** [comment]
This build might work a little better:
https://github.com/the-hideout/TarkovMonitor/actions/runs/7901748702/artifacts/1244729021

**Comment by CBTB11235813** [comment]
That worked a little better, though not 100%. Got this error message: 

![image](https://github.com/the-hideout/TarkovMonitor/assets/26905882/f458f884-6d85-4b71-b790-866a39d4f30e)

I went to messages, and it showed the most recent quests I had completed.

![image](https://github.com/the-hideout/TarkovMonitor/assets/26905882/b944395c-8bbf-4d2a-a7f7-a3cfa6d9575b)

It doesn't seem to be telling Tarkov Tracker those quests are completed, and when I go to my stats tab it shows no data.

**Comment by Razzmatazzz** [comment]
I just tested it now and it worked to update a couple of quests I manually marked as not completed in Tarkov Tracker. That error indicates the Tarkov Tracker API had an error processing the request. Do you have any problems with Tarkov Monitor updating your quest progress in real time as you play?

**Comment by Razzmatazzz** [comment]
Good to hear it seems to be working now!

Tarkov Monitor can't automatically update your PMC level because that number isn't logged. Tarkov Tracker will automatically update your PMC level if a quest you complete requires a level higher than your current PMC level. So I would infer that none of the quests completed have a minimum level greater than 12.
