### ISSUE TITLE
Tarkov.dev Map Position Updates Not Working in Practice Mode

### ISSUE THREAD

**Issue by ten9miq** [the-hideout/TarkovMonitor#61]
Hello,
I've encountered an issue where map position updates are not working when I start a raid in Practice Mode on Tarkov.dev. Is it possible to make updates work in Practice Mode as well?
Thank you for providing such an amazing tool. I appreciate the hard work and effort that goes into maintaining it.

**Comment by Razzmatazzz** [comment]
Unfortunately, the game doesn't log enough when loading into an offline raid to know which map is being played.

**Comment by ten9miq** [comment]
Thank you for your response to my previous message regarding the issue where map position updates are not working when starting a raid in Practice Mode on Tarkov.dev. I understand from your reply that the game doesn't log enough information when loading into an offline raid to determine which map is being played.

Considering this limitation, could an alternative solution be implemented, such as allowing users to manually select the map they are practicing on? This could potentially bypass the need for automatic detection and still provide value for users looking to familiarize themselves with different map layouts in Practice Mode.

**Comment by Razzmatazzz** [comment]
I'll look into whether it's possible. Not sure if the game logs enough to even really show that an offline raid is loading. If it's possible to detect an offline is loading, may be possible to update the player's position on an "unknown" map, which would then just display on every map.

**Comment by Razzmatazzz** [comment]
I've looked into it and the game doesn't log enough information when going into an offline raid to make it simple to trigger an event for offline raids without messing up (or greatly complicating) the code for online raids. Because online raids are the priority, I won't be putting in the development time needed to make this happen.

**Comment by ten9miq** [comment]
That's disappointing to hear.
It was one of the features I was looking forward to, so it's a letdown to learn it won't be happening.
However, I understand the priorities in development and the limited resources available.
I look forward to continuing to enjoy the updates and evolution.
Thank you.

**Comment by Razzmatazzz** [comment]
Making this note here as a reminder to myself: Someone suggested on Discord adding the ability to set the current map manually, which would then allow the screenshot function to work. I should be able to add that in a future release.
