### ISSUE TITLE
Screenshot for map position help

### ISSUE THREAD

**Issue by adamyonk** [the-hideout/TarkovMonitor#62]
I don't think I understand how this is supposed to work - you take a screenshot of Tarkov when you load into a raid or something? Does it need to be specifically with the built-in snip tool? My screenshots seem to save to Pictures > Screenshots, but the code looks like it's watching for the Documents folder.

**Comment by Killertom63** [comment]
- Navigate to [Tarkov.dev/map](https://tarkov.dev/map)
- Click the ? in the bottom left or the bottom right to get a code. 
- Open TarkovMonitor, go to settings, input the code.
- Go back to [Tarkov.dev/control](https://tarkov.dev/control/) put the same code in and press connect.
- Now when you join a raid it'll show you the map that you're playing. If you screen shot it'll drop a pin where you are. 

Please note, you'll have to hit "connect" on Tarkov.dev/control everytime you reopen the website.

**Comment by adamyonk** [comment]
Thanks! The screenshot bit is the part I'm not understanding, just screenshot the EFT window when your raid starts? Does the screenshot have to be saved in a particular place?

**Comment by Razzmatazzz** [comment]
@adamyonk did this answer your question?

**Comment by adamyonk** [comment]
Yes, I was able to get it working. Awesome feature!
