### ISSUE TITLE
error 500 while updating task progression

### ISSUE THREAD

**Issue by wchristian** [the-hideout/TarkovMonitor#67]
"copy" only gives me the below. does tarkovmonitor have a log i can get more useful info out of?

`Error updating Tarkov Tracker task progression: Invalid TarkovTracker API response code: Response status code does not indicate success: 500 (Internal Server Error).`

![image](https://github.com/the-hideout/TarkovMonitor/assets/175467/a8f6a1c8-6185-4db8-a50b-d0f88278765a)

**Comment by M3ragon** [comment]
got the same error, try to restart the tool on "adminmode", this fixed the error for me
