### ISSUE TITLE
clicking "copy" on error results in js error as well

### ISSUE THREAD

**Issue by wchristian** [the-hideout/TarkovMonitor#68]
`Error in message button: $Object reference not set to an instance of an object.    at TarkovMonitor.Blazor.Components.MessageBoard.MessageButtonClick(MonitorMessageButton button) in TarkovMonitor\Blazor\Components\MessageBoard.razor:line 147`

![image](https://github.com/the-hideout/TarkovMonitor/assets/175467/bbd594e2-1228-48dd-a884-8e95051180f0)

**Comment by Razzmatazzz** [comment]
Nevermind, I figured it out. Closing this as a duplicate of #66

**Comment by Razzmatazzz** [comment]
Thanks for reporting!
